#!/usr/bin/env zsh

setopt extended_glob

cd $(dirname $0)

# New cabal apparently can't be run in a subdir, but gives a confusing error.
root=$(cd .. && pwd)

# bin=../../dist/build/fix-imports/fix-imports
# bin=(cabal run --builddir=$root fix-imports --)
bin=../../dist-newstyle/build/x86_64-osx/ghc-8.8.3/fix-imports-2.3.0/x/fix-imports/build/fix-imports/fix-imports

tests=($@)
if [[ -z $tests ]]; then
    tests=($(echo *(/)))
fi

tmp=$(mktemp -t fix-imports)

function test() {
    pushd $1
    local flags=
    if [[ -r flags ]]; then
        flags=$(cat flags)
    fi
    echo $bin ${=flags}
    $bin ${=flags} Main.hs <Main.hs >& $tmp
    diff $tmp expected
    local failed=$?
    if [[ $failed != 0 ]]; then
        echo '==== expected:'
        cat expected
        echo '==== got:'
        cat $tmp
    fi
    popd
    return $failed
}

failed=0
for test in $tests; do
    if ! test $test; then
        echo $test FAILED
        failed=1
    else
        echo $test passed
    fi
    echo
done

rm -f $tmp
exit $failed
